import {
  Store,
  StoreManager,
  FoodItem,
  MenuCategory,
  Order,
  IssueTicket,
  NotificationItem,
} from '../types';

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-kfc-01',
    name: 'KFC - Food Street',
    tagline: "It's Finger Lickin' Good",
    description: 'Crispy fried chicken, zesty burgers, crunch meals & refreshing beverages made fresh on order.',
    logo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=200&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    contactNumber: '+91 98450 12345',
    email: 'kfc.foodstreet@deliveryapp.in',
    address: 'Shop 14-16, Ground Floor, Food Street Galleria, 80 Feet Road, Koramangala 4th Block',
    locationArea: 'Koramangala 4th Block',
    city: 'Bengaluru',
    openingTime: '10:00',
    closingTime: '23:30',
    isOpen: true,
    defaultTimeoutSeconds: 60,
    defaultPrepTimeMinutes: 20,
    rating: 4.6,
    totalReviews: 1420,
    ownerName: 'Yum! Brands India Retail Pvt Ltd',
    storeOwnerId: 'CORP-YUM-892',
    commissionPercentage: 18.5,
    gstin: '29AAACK3921Q1Z9',
    fssaiLicense: '11221334000512',
  },
  {
    id: 'store-dom-02',
    name: "Domino's Pizza - Central Hub",
    tagline: 'Hot & Fresh Pizzas Delivered in 30 Mins',
    description: 'Hand-tossed cheesy pizzas, garlic breads, choco lava cakes, and gourmet pasta.',
    logo: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=200&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    contactNumber: '+91 98860 55432',
    email: 'dominos.central@deliveryapp.in',
    address: 'Plot 22, 100 Feet Ring Road, Indiranagar',
    locationArea: 'Indiranagar',
    city: 'Bengaluru',
    openingTime: '11:00',
    closingTime: '01:00',
    isOpen: true,
    defaultTimeoutSeconds: 60,
    defaultPrepTimeMinutes: 25,
    rating: 4.7,
    totalReviews: 2180,
    ownerName: 'Jubilant FoodWorks Ltd',
    storeOwnerId: 'CORP-JUB-441',
    commissionPercentage: 18.5,
    gstin: '29AABCS8823M1Z2',
    fssaiLicense: '11221334000889',
  },
  {
    id: 'store-bk-03',
    name: 'Burger King - Tech Park',
    tagline: 'Taste Is King',
    description: 'Flame-grilled Whoppers, crunchy fries, thick milkshakes and breakfast wraps.',
    logo: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=200&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80',
    contactNumber: '+91 97410 99881',
    email: 'bk.techpark@deliveryapp.in',
    address: 'Building 4, EcoWorld Technology Park, Outer Ring Road, Bellandur',
    locationArea: 'Bellandur',
    city: 'Bengaluru',
    openingTime: '09:00',
    closingTime: '23:00',
    isOpen: false,
    defaultTimeoutSeconds: 60,
    defaultPrepTimeMinutes: 18,
    rating: 4.5,
    totalReviews: 960,
    ownerName: 'Restaurant Brands Asia Ltd',
    storeOwnerId: 'CORP-RBA-771',
    commissionPercentage: 18.0,
    gstin: '29AABCR4410K1ZX',
    fssaiLicense: '11221334000301',
  },
];

export const INITIAL_MANAGERS: StoreManager[] = [
  {
    id: 'MGR-KFC-101',
    storeId: 'store-kfc-01',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@kfcstore.in',
    phone: '+91 98450 12345',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    role: 'STORE_MANAGER',
    lastLogin: 'Today at 09:45 AM',
  },
  {
    id: 'MGR-DOM-202',
    storeId: 'store-dom-02',
    name: 'Priya Sen',
    email: 'priya.sen@dominosindia.com',
    phone: '+91 98860 55432',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    role: 'STORE_MANAGER',
    lastLogin: 'Today at 10:15 AM',
  },
  {
    id: 'MGR-BK-303',
    storeId: 'store-bk-03',
    name: 'Amit Verma',
    email: 'amit.verma@burgerking.in',
    phone: '+91 97410 99881',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    role: 'STORE_MANAGER',
    lastLogin: 'Yesterday at 06:30 PM',
  },
];

export const INITIAL_CATEGORIES: MenuCategory[] = [
  // KFC Categories
  { id: 'cat-kfc-1', storeId: 'store-kfc-01', name: 'Burgers', description: 'Crispy chicken & veggie burgers', displayOrder: 1 },
  { id: 'cat-kfc-2', storeId: 'store-kfc-01', name: 'Buckets & Chicken', description: 'Signature hot & crispy chicken', displayOrder: 2 },
  { id: 'cat-kfc-3', storeId: 'store-kfc-01', name: 'Rolls & Bowls', description: 'Quick rice bowls & chicken rolls', displayOrder: 3 },
  { id: 'cat-kfc-4', storeId: 'store-kfc-01', name: 'Beverages', description: 'Chilled soft drinks & coolers', displayOrder: 4 },
  { id: 'cat-kfc-5', storeId: 'store-kfc-01', name: 'Desserts', description: 'Sweet treats & pies', displayOrder: 5 },

  // Domino's Categories
  { id: 'cat-dom-1', storeId: 'store-dom-02', name: 'Veg Pizzas', description: 'Farm fresh vegetable pizzas', displayOrder: 1 },
  { id: 'cat-dom-2', storeId: 'store-dom-02', name: 'Non-Veg Pizzas', description: 'Loaded chicken & pepperoni pizzas', displayOrder: 2 },
  { id: 'cat-dom-3', storeId: 'store-dom-02', name: 'Sides & Garlic Breads', description: 'Cheesy sides and dips', displayOrder: 3 },
  { id: 'cat-dom-4', storeId: 'store-dom-02', name: 'Desserts & Drinks', description: 'Choco lava & cold drinks', displayOrder: 4 },

  // BK Categories
  { id: 'cat-bk-1', storeId: 'store-bk-03', name: 'Whoppers', description: 'Flame grilled signature Whoppers', displayOrder: 1 },
  { id: 'cat-bk-2', storeId: 'store-bk-03', name: 'Crispy Burgers', description: 'Value crispy burgers', displayOrder: 2 },
  { id: 'cat-bk-3', storeId: 'store-bk-03', name: 'Sides & Fries', description: 'King fries & chicken nuggets', displayOrder: 3 },
];

export const INITIAL_FOOD_ITEMS: FoodItem[] = [
  // KFC Menu Items
  {
    id: 'item-kfc-1',
    storeId: 'store-kfc-01',
    name: 'Chicken Burger',
    description: 'Crispy fried chicken patty topped with crunchy iceberg lettuce and creamy mayo on a toasted sesame bun.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80',
    price: 129,
    category: 'Burgers',
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 12,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-kfc-2',
    storeId: 'store-kfc-01',
    name: 'Veg Burger',
    description: 'Golden fried vegetable patty made with green peas, potatoes, carrots, spiced mayo and fresh lettuce.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&auto=format&fit=crop&q=80',
    price: 99,
    category: 'Burgers',
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 10,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-kfc-3',
    storeId: 'store-kfc-01',
    name: 'Pepsi Can 330ml',
    description: 'Chilled 330ml can of refreshing carbonated Pepsi cola.',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&auto=format&fit=crop&q=80',
    price: 40,
    category: 'Beverages',
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 2,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-kfc-4',
    storeId: 'store-kfc-01',
    name: 'Hot & Crispy Chicken (4 pcs)',
    description: '4 pieces of legendary bone-in chicken marinated in secret spices and fried to golden crispiness.',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&auto=format&fit=crop&q=80',
    price: 399,
    category: 'Buckets & Chicken',
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 15,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-kfc-5',
    storeId: 'store-kfc-01',
    name: 'Zinger Burger Pro',
    description: 'Signature juicy whole chicken breast fillet with spicy crunch, melted cheese and jalapeño mayo.',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=400&auto=format&fit=crop&q=80',
    price: 199,
    category: 'Burgers',
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 14,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-kfc-6',
    storeId: 'store-kfc-01',
    name: 'Peri Peri Chicken Strips (6 pcs)',
    description: 'Tender boneless chicken tenders dusted with spicy African bird eye peri-peri seasoning.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400&auto=format&fit=crop&q=80',
    price: 249,
    category: 'Buckets & Chicken',
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 10,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-kfc-7',
    storeId: 'store-kfc-01',
    name: 'Popcorn Chicken Rice Bowl',
    description: 'Steamy fragrant aromatic rice topped with crunchy hot popcorn chicken & spicy pepper gravy.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&auto=format&fit=crop&q=80',
    price: 219,
    category: 'Rolls & Bowls',
    isVeg: false,
    isAvailable: false, // Currently out of stock example
    preparationTimeMinutes: 12,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-kfc-8',
    storeId: 'store-kfc-01',
    name: 'Choco Lava Cake',
    description: 'Warm, soft chocolate mini-cake with a molten gooey chocolate center.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&auto=format&fit=crop&q=80',
    price: 99,
    category: 'Desserts',
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 5,
    createdAt: '2026-01-15T10:00:00Z',
  },

  // Domino's Items
  {
    id: 'item-dom-1',
    storeId: 'store-dom-02',
    name: 'Farmhouse Veggie Pizza',
    description: 'Delightful combination of onion, capsicum, tomato & grilled mushroom with 100% mozzarella.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&auto=format&fit=crop&q=80',
    price: 349,
    category: 'Veg Pizzas',
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 18,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-dom-2',
    storeId: 'store-dom-02',
    name: 'Pepper Barbecue Chicken Pizza',
    description: 'Pepper barbecue chicken for that flavorful, smoky kick topped with liquid cheese.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&auto=format&fit=crop&q=80',
    price: 449,
    category: 'Non-Veg Pizzas',
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 20,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'item-dom-3',
    storeId: 'store-dom-02',
    name: 'Stuffed Garlic Breadsticks',
    description: 'Freshly baked garlic breadsticks stuffed with cheesy jalapeños and sweet corn.',
    image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=400&auto=format&fit=crop&q=80',
    price: 159,
    category: 'Sides & Garlic Breads',
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 12,
    createdAt: '2026-01-15T10:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  // Active / Preparing Order 1 (e.g., KFC)
  {
    id: 'FC1024',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-901',
      name: 'Aakash Verma',
      phone: '+91 98711 22334',
      deliveryAddress: 'Block C, Room 304, Stanza Living PG, 5th Cross Road',
      hostelOrPg: 'Stanza Living PG',
      roomNumber: '304',
    },
    items: [
      { id: 'item-kfc-1', name: 'Chicken Burger', price: 129, quantity: 2, isVeg: false },
      { id: 'item-kfc-3', name: 'Pepsi Can 330ml', price: 40, quantity: 1, isVeg: true },
    ],
    subtotal: 298,
    deliveryFee: 40,
    tax: 0,
    total: 338,
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    status: 'PREPARING',
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '12:15 PM', note: 'Customer placed order' },
      { status: 'MANAGER_ACCEPTED', timestamp: '12:16 PM', note: 'Manager accepted order' },
      { status: 'PREPARING', timestamp: '12:18 PM', note: 'Kitchen started preparation' },
    ],
    createdAt: '2026-08-30T12:15:00Z',
    timeoutSeconds: 60,
    prepTimeMinutes: 15,
    deliveryPartner: {
      id: 'dp-501',
      name: 'Rajesh Kumar',
      phone: '+91 99112 33445',
      vehicleNumber: 'KA-03-EB-4921',
      vehicleType: 'TVS Jupiter',
      rating: 4.8,
      estimatedArrivalMinutes: 6,
      status: 'ARRIVING_AT_STORE',
    },
  },
  // Active Order 2 (Accepted, waiting kitchen start)
  {
    id: 'FC1025',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-902',
      name: 'Sneha Patel',
      phone: '+91 97321 88990',
      deliveryAddress: 'Flat 402, Oakwood Residency, 17th Main Road',
      hostelOrPg: 'Oakwood Residency',
      roomNumber: '402',
    },
    items: [
      { id: 'item-kfc-5', name: 'Zinger Burger Pro', price: 199, quantity: 1, isVeg: false },
      { id: 'item-kfc-6', name: 'Peri Peri Chicken Strips (6 pcs)', price: 249, quantity: 1, isVeg: false },
      { id: 'item-kfc-3', name: 'Pepsi Can 330ml', price: 40, quantity: 2, isVeg: true },
    ],
    subtotal: 528,
    deliveryFee: 40,
    tax: 0,
    total: 568,
    paymentMethod: 'CARD',
    paymentStatus: 'PAID',
    status: 'MANAGER_ACCEPTED',
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '12:22 PM', note: 'Customer placed order' },
      { status: 'MANAGER_ACCEPTED', timestamp: '12:23 PM', note: 'Manager accepted order' },
    ],
    createdAt: '2026-08-30T12:22:00Z',
    timeoutSeconds: 60,
    prepTimeMinutes: 20,
    deliveryPartner: {
      id: 'dp-502',
      name: 'Manish Gowda',
      phone: '+91 98822 44556',
      vehicleNumber: 'KA-05-MN-1188',
      vehicleType: 'Honda Activa',
      rating: 4.9,
      estimatedArrivalMinutes: 10,
      status: 'ASSIGNED',
    },
  },
  // Active Order 3 (Ready for pickup)
  {
    id: 'FC1023',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-903',
      name: 'Karthik Raja',
      phone: '+91 99001 77665',
      deliveryAddress: 'Hostel 4, Room B-12, RV College of Engineering',
      hostelOrPg: 'RVCE Boys Hostel 4',
      roomNumber: 'B-12',
    },
    items: [
      { id: 'item-kfc-4', name: 'Hot & Crispy Chicken (4 pcs)', price: 399, quantity: 1, isVeg: false },
      { id: 'item-kfc-8', name: 'Choco Lava Cake', price: 99, quantity: 2, isVeg: true },
    ],
    subtotal: 597,
    deliveryFee: 30,
    tax: 0,
    total: 627,
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    status: 'READY_FOR_PICKUP',
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '12:00 PM', note: 'Customer placed order' },
      { status: 'MANAGER_ACCEPTED', timestamp: '12:01 PM', note: 'Manager accepted order' },
      { status: 'PREPARING', timestamp: '12:03 PM', note: 'Kitchen preparing' },
      { status: 'READY_FOR_PICKUP', timestamp: '12:20 PM', note: 'Food packaged and placed at pickup counter' },
    ],
    createdAt: '2026-08-30T12:00:00Z',
    timeoutSeconds: 60,
    prepTimeMinutes: 18,
    deliveryPartner: {
      id: 'dp-503',
      name: 'Vikram Singh',
      phone: '+91 97400 66551',
      vehicleNumber: 'KA-01-JK-7820',
      vehicleType: 'Bajaj Pulsar 150',
      rating: 4.7,
      estimatedArrivalMinutes: 2,
      status: 'ARRIVING_AT_STORE',
    },
  },
  // Active Order 4 (Out for delivery)
  {
    id: 'FC1022',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-904',
      name: 'Ananya Roy',
      phone: '+91 96111 44332',
      deliveryAddress: 'Tower 2, Apt 1104, Prestige Acropolis',
      hostelOrPg: 'Prestige Acropolis',
      roomNumber: '1104',
    },
    items: [
      { id: 'item-kfc-2', name: 'Veg Burger', price: 99, quantity: 2, isVeg: true },
      { id: 'item-kfc-3', name: 'Pepsi Can 330ml', price: 40, quantity: 2, isVeg: true },
    ],
    subtotal: 278,
    deliveryFee: 40,
    tax: 0,
    total: 318,
    paymentMethod: 'CASH_ON_DELIVERY',
    paymentStatus: 'PENDING',
    status: 'OUT_FOR_DELIVERY',
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '11:45 AM', note: 'Placed' },
      { status: 'MANAGER_ACCEPTED', timestamp: '11:46 AM', note: 'Accepted' },
      { status: 'PREPARING', timestamp: '11:48 AM', note: 'Preparing' },
      { status: 'READY_FOR_PICKUP', timestamp: '12:05 PM', note: 'Food Ready' },
      { status: 'OUT_FOR_DELIVERY', timestamp: '12:12 PM', note: 'Delivery partner picked up parcel' },
    ],
    createdAt: '2026-08-30T11:45:00Z',
    timeoutSeconds: 60,
    deliveryPartner: {
      id: 'dp-504',
      name: 'Suresh Babu',
      phone: '+91 98440 22119',
      vehicleNumber: 'KA-04-TR-9031',
      vehicleType: 'Hero Splendor',
      rating: 4.8,
      estimatedArrivalMinutes: 8,
      status: 'ON_THE_WAY',
    },
  },
  // Historical Delivered Orders (Today)
  {
    id: 'FC1021',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-905',
      name: 'Rohan Deshmukh',
      phone: '+91 98201 11223',
      deliveryAddress: 'Flat 102, Green Glen Layout, Bellandur',
      hostelOrPg: 'Green Glen Residency',
      roomNumber: '102',
    },
    items: [
      { id: 'item-kfc-5', name: 'Zinger Burger Pro', price: 199, quantity: 2, isVeg: false },
      { id: 'item-kfc-4', name: 'Hot & Crispy Chicken (4 pcs)', price: 399, quantity: 1, isVeg: false },
    ],
    subtotal: 797,
    deliveryFee: 40,
    tax: 0,
    total: 837,
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    status: 'DELIVERED',
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '11:10 AM' },
      { status: 'MANAGER_ACCEPTED', timestamp: '11:11 AM' },
      { status: 'PREPARING', timestamp: '11:13 AM' },
      { status: 'READY_FOR_PICKUP', timestamp: '11:28 AM' },
      { status: 'OUT_FOR_DELIVERY', timestamp: '11:32 AM' },
      { status: 'DELIVERED', timestamp: '11:52 AM', note: 'Customer confirmed delivery' },
    ],
    createdAt: '2026-08-30T11:10:00Z',
    timeoutSeconds: 60,
    deliveryPartner: {
      id: 'dp-505',
      name: 'Imran Khan',
      phone: '+91 97311 00998',
      vehicleNumber: 'KA-02-ML-3341',
      vehicleType: 'Suzuki Access',
      rating: 4.9,
      status: 'DELIVERED',
    },
  },
  {
    id: 'FC1020',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-906',
      name: 'Divya Nambiar',
      phone: '+91 99887 76655',
      deliveryAddress: 'Room 210, Zolo Stays, HSR Sector 2',
      hostelOrPg: 'Zolo Stays PG',
      roomNumber: '210',
    },
    items: [
      { id: 'item-kfc-1', name: 'Chicken Burger', price: 129, quantity: 1, isVeg: false },
      { id: 'item-kfc-8', name: 'Choco Lava Cake', price: 99, quantity: 1, isVeg: true },
      { id: 'item-kfc-3', name: 'Pepsi Can 330ml', price: 40, quantity: 1, isVeg: true },
    ],
    subtotal: 268,
    deliveryFee: 30,
    tax: 0,
    total: 298,
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    status: 'DELIVERED',
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '10:35 AM' },
      { status: 'MANAGER_ACCEPTED', timestamp: '10:36 AM' },
      { status: 'PREPARING', timestamp: '10:38 AM' },
      { status: 'READY_FOR_PICKUP', timestamp: '10:50 AM' },
      { status: 'OUT_FOR_DELIVERY', timestamp: '10:55 AM' },
      { status: 'DELIVERED', timestamp: '11:15 AM' },
    ],
    createdAt: '2026-08-30T10:35:00Z',
    timeoutSeconds: 60,
  },
  {
    id: 'FC1019',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-907',
      name: 'Manoj Hegde',
      phone: '+91 94480 33211',
      deliveryAddress: '3rd Floor, Tech Corp India, Cessna Business Park',
      hostelOrPg: 'Cessna Tech Park',
      roomNumber: 'Desk 34',
    },
    items: [
      { id: 'item-kfc-6', name: 'Peri Peri Chicken Strips (6 pcs)', price: 249, quantity: 2, isVeg: false },
      { id: 'item-kfc-3', name: 'Pepsi Can 330ml', price: 40, quantity: 2, isVeg: true },
    ],
    subtotal: 578,
    deliveryFee: 40,
    tax: 0,
    total: 618,
    paymentMethod: 'NET_BANKING',
    paymentStatus: 'PAID',
    status: 'DELIVERED',
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '10:15 AM' },
      { status: 'MANAGER_ACCEPTED', timestamp: '10:16 AM' },
      { status: 'DELIVERED', timestamp: '10:50 AM' },
    ],
    createdAt: '2026-08-30T10:15:00Z',
    timeoutSeconds: 60,
  },
  // Rejected Order
  {
    id: 'FC1018',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-908',
      name: 'Naveen Kumar',
      phone: '+91 98801 44552',
      deliveryAddress: 'Flat 12, Sunrise Apts',
    },
    items: [
      { id: 'item-kfc-7', name: 'Popcorn Chicken Rice Bowl', price: 219, quantity: 2, isVeg: false },
    ],
    subtotal: 438,
    deliveryFee: 40,
    tax: 0,
    total: 478,
    paymentMethod: 'UPI',
    paymentStatus: 'REFUNDED',
    status: 'ORDER_CANCELLED',
    rejectionReason: 'Ingredient out of stock (Popcorn Chicken Rice Bowl)',
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '09:50 AM', note: 'Placed' },
      { status: 'MANAGER_REJECTED', timestamp: '09:51 AM', note: 'Rejected by manager: Out of stock' },
      { status: 'ORDER_CANCELLED', timestamp: '09:51 AM', note: 'Order cancelled, customer refunded' },
    ],
    createdAt: '2026-08-30T09:50:00Z',
    timeoutSeconds: 60,
  },
  // Manager Timeout Order
  {
    id: 'FC1017',
    storeId: 'store-kfc-01',
    customer: {
      id: 'cust-909',
      name: 'Tarun Joshi',
      phone: '+91 97722 33441',
      deliveryAddress: 'Block A, PG 101',
    },
    items: [
      { id: 'item-kfc-1', name: 'Chicken Burger', price: 129, quantity: 1, isVeg: false },
    ],
    subtotal: 129,
    deliveryFee: 30,
    tax: 0,
    total: 159,
    paymentMethod: 'UPI',
    paymentStatus: 'REFUNDED',
    status: 'MANAGER_TIMEOUT',
    adminEscalated: true,
    statusHistory: [
      { status: 'WAITING_FOR_MANAGER', timestamp: '09:30 AM' },
      { status: 'MANAGER_TIMEOUT', timestamp: '09:31 AM', note: 'Manager did not respond within 60s. Escalated to Admin.' },
    ],
    createdAt: '2026-08-30T09:30:00Z',
    timeoutSeconds: 60,
  },
];

export const INITIAL_ISSUES: IssueTicket[] = [
  {
    id: '#ISSUE1024',
    storeId: 'store-kfc-01',
    managerId: 'MGR-KFC-101',
    category: 'Delivery issue',
    relatedOrderId: 'FC1024',
    subject: 'Delivery partner has not arrived for pickup #FC1024',
    status: 'OPEN',
    priority: 'HIGH',
    messages: [
      {
        id: 'msg-1',
        sender: 'MANAGER',
        senderName: 'Rajesh Sharma (Store Manager)',
        message: 'Delivery partner has not arrived for pickup. Order #FC1024 is ready and getting cold on the pickup counter.',
        timestamp: '12:25 PM',
      },
      {
        id: 'msg-2',
        sender: 'ADMIN',
        senderName: 'Central Ops Admin (Pooja)',
        message: 'I am checking the delivery assignment. Delivery Partner Rajesh Kumar is stuck in junction traffic 400m away, reaching in 2 minutes.',
        timestamp: '12:27 PM',
      },
    ],
    createdAt: '2026-08-30T12:25:00Z',
    updatedAt: '2026-08-30T12:27:00Z',
  },
  {
    id: '#ISSUE1019',
    storeId: 'store-kfc-01',
    managerId: 'MGR-KFC-101',
    category: 'Payment issue',
    relatedOrderId: 'FC1019',
    subject: 'NetBanking payment reconciliation discrepancy',
    status: 'RESOLVED',
    priority: 'MEDIUM',
    messages: [
      {
        id: 'msg-3',
        sender: 'MANAGER',
        senderName: 'Rajesh Sharma (Store Manager)',
        message: 'Payment status showed delayed capture for Order #FC1019. Please verify settlement report.',
        timestamp: '10:40 AM',
      },
      {
        id: 'msg-4',
        sender: 'ADMIN',
        senderName: 'Finance Admin',
        message: 'Verified with payment gateway webhook. Amount ₹618 successfully credited to store payout account.',
        timestamp: '11:05 AM',
      },
    ],
    createdAt: '2026-08-30T10:40:00Z',
    updatedAt: '2026-08-30T11:05:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    storeId: 'store-kfc-01',
    type: 'DELIVERY_PARTNER_ASSIGNED',
    title: 'Delivery Partner Assigned',
    message: 'Rajesh Kumar (KA-03-EB-4921) assigned to Order #FC1024. ETA 6 mins.',
    orderId: 'FC1024',
    timestamp: '12:19 PM',
    isRead: false,
  },
  {
    id: 'notif-2',
    storeId: 'store-kfc-01',
    type: 'ADMIN_MESSAGE',
    title: 'Admin Replied to Issue #ISSUE1024',
    message: 'Central Ops Admin replied regarding delivery assignment update.',
    issueId: '#ISSUE1024',
    timestamp: '12:27 PM',
    isRead: false,
  },
  {
    id: 'notif-3',
    storeId: 'store-kfc-01',
    type: 'PLATFORM_ANNOUNCEMENT',
    title: '⚡ Weekend Monsoon Surge Promo Active',
    message: 'Zero delivery fee active for Koramangala area orders above ₹299. Expect 35% higher order volume.',
    timestamp: '10:00 AM',
    isRead: true,
  },
];
