import {
  AdminUser,
  Store,
  StoreManager,
  DeliveryPartner,
  MenuCategory,
  MenuItem,
  Order,
  Offer,
  NotificationLog,
} from '../types';

export const INITIAL_ADMIN: AdminUser = {
  id: 'adm_001',
  adminId: 'ADMIN100',
  name: 'Vikramaditya Rao',
  email: 'admin@foodfleet.internal',
  role: 'ADMIN',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  lastLogin: 'Today at 09:15 AM',
};

export const INITIAL_STORES: Store[] = [
  {
    id: 'store_kfc',
    name: 'KFC',
    logo: 'https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?w=150&auto=format&fit=crop&q=80',
    description: 'Crispy fried chicken, zinger burgers, chicken popcorn and chilled beverages.',
    location: 'Food Street, Near University North Gate',
    contactNumber: '+91 98765 43210',
    openingTime: '10:00 AM',
    closingTime: '11:30 PM',
    status: 'Active',
    managerId: 'mgr_rahul',
    managerName: 'Rahul Sharma',
    rating: 4.5,
    totalOrders: 642,
    totalSales: 218400,
    createdAt: '2026-01-15',
  },
  {
    id: 'store_pizzahut',
    name: 'Pizza Hut',
    logo: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=150&auto=format&fit=crop&q=80',
    description: 'Pan pizzas, cheesy garlic bread, pastas and decadent desserts.',
    location: 'Central Avenue, Sector 14 Market',
    contactNumber: '+91 98765 43211',
    openingTime: '11:00 AM',
    closingTime: '11:00 PM',
    status: 'Active',
    managerId: 'mgr_priya',
    managerName: 'Priya Patel',
    rating: 4.3,
    totalOrders: 498,
    totalSales: 189200,
    createdAt: '2026-01-20',
  },
  {
    id: 'store_subway',
    name: 'Subway',
    logo: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=150&auto=format&fit=crop&q=80',
    description: 'Fresh customizable submarine sandwiches, wholesome salads and cookies.',
    location: 'Tech Park Plaza, 1st Floor Food Court',
    contactNumber: '+91 98765 43212',
    openingTime: '08:30 AM',
    closingTime: '10:30 PM',
    status: 'Active',
    managerId: 'mgr_amit',
    managerName: 'Amit Verma',
    rating: 4.4,
    totalOrders: 380,
    totalSales: 114000,
    createdAt: '2026-02-01',
  },
  {
    id: 'store_burgerking',
    name: 'Burger King',
    logo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=150&auto=format&fit=crop&q=80',
    description: 'Flame-grilled whoppers, crispy fries, thick shakes and wraps.',
    location: 'Main Ring Road, Opp. Metro Pillar 114',
    contactNumber: '+91 98765 43213',
    openingTime: '09:00 AM',
    closingTime: '01:00 AM',
    status: 'Active',
    managerId: 'mgr_sanjay',
    managerName: 'Sanjay Gupta',
    rating: 4.2,
    totalOrders: 512,
    totalSales: 163800,
    createdAt: '2026-02-05',
  },
  {
    id: 'store_biryani',
    name: 'Biryani Blues',
    logo: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=150&auto=format&fit=crop&q=80',
    description: 'Authentic Hyderabadi Dum Biryani, kebabs, mirchi ka salan and gulab jamun.',
    location: 'Hostel Square, Behind Block C',
    contactNumber: '+91 98765 43214',
    openingTime: '12:00 PM',
    closingTime: '11:00 PM',
    status: 'Active',
    managerId: 'mgr_ananya',
    managerName: 'Ananya Deshmukh',
    rating: 4.7,
    totalOrders: 730,
    totalSales: 292000,
    createdAt: '2026-02-10',
  },
  {
    id: 'store_chaipoint',
    name: 'Chai Point & Snacks',
    logo: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=150&auto=format&fit=crop&q=80',
    description: 'Hot brewed ginger & masala chai, samosas, bun maska and maggi bowls.',
    location: 'Library Corner, Academic Block',
    contactNumber: '+91 98765 43215',
    openingTime: '07:30 AM',
    closingTime: '10:00 PM',
    status: 'Active',
    managerId: 'mgr_vikas',
    managerName: 'Vikas Nair',
    rating: 4.6,
    totalOrders: 910,
    totalSales: 118300,
    createdAt: '2026-02-12',
  },
  {
    id: 'store_wowmomo',
    name: 'Wow! Momo',
    logo: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=150&auto=format&fit=crop&q=80',
    description: 'Steamed, fried & pan-fried momos, moburgs and spicy thukpa.',
    location: 'Student Activity Center, Stall 4',
    contactNumber: '+91 98765 43216',
    openingTime: '11:00 AM',
    closingTime: '10:30 PM',
    status: 'Inactive',
    managerId: 'mgr_neha',
    managerName: 'Neha Singh',
    rating: 4.1,
    totalOrders: 210,
    totalSales: 54600,
    createdAt: '2026-03-01',
  },
  {
    id: 'store_rolls',
    name: 'Rolls & Bowls',
    logo: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=150&auto=format&fit=crop&q=80',
    description: 'Kolkata kathi rolls, paneer wraps, egg chicken rolls and rice bowls.',
    location: 'Girls Hostel Back Gate, Stall 2',
    contactNumber: '+91 98765 43217',
    openingTime: '12:30 PM',
    closingTime: '12:00 AM',
    status: 'Active',
    managerId: 'mgr_karan',
    managerName: 'Karan Mehra',
    rating: 4.3,
    totalOrders: 320,
    totalSales: 76800,
    createdAt: '2026-03-10',
  },
];

export const INITIAL_MANAGERS: StoreManager[] = [
  {
    id: 'mgr_rahul',
    name: 'Rahul Sharma',
    phoneNumber: '+91 98111 22334',
    email: 'rahul.kfc@foodfleet.store',
    loginId: 'MGR_KFC_01',
    assignedStoreId: 'store_kfc',
    assignedStoreName: 'KFC',
    status: 'Active',
    joinedDate: '2026-01-15',
    totalOrdersManaged: 642,
  },
  {
    id: 'mgr_priya',
    name: 'Priya Patel',
    phoneNumber: '+91 98222 33445',
    email: 'priya.pizzahut@foodfleet.store',
    loginId: 'MGR_PIZZA_02',
    assignedStoreId: 'store_pizzahut',
    assignedStoreName: 'Pizza Hut',
    status: 'Active',
    joinedDate: '2026-01-20',
    totalOrdersManaged: 498,
  },
  {
    id: 'mgr_amit',
    name: 'Amit Verma',
    phoneNumber: '+91 98333 44556',
    email: 'amit.subway@foodfleet.store',
    loginId: 'MGR_SUBWAY_03',
    assignedStoreId: 'store_subway',
    assignedStoreName: 'Subway',
    status: 'Active',
    joinedDate: '2026-02-01',
    totalOrdersManaged: 380,
  },
  {
    id: 'mgr_sanjay',
    name: 'Sanjay Gupta',
    phoneNumber: '+91 98444 55667',
    email: 'sanjay.bk@foodfleet.store',
    loginId: 'MGR_BK_04',
    assignedStoreId: 'store_burgerking',
    assignedStoreName: 'Burger King',
    status: 'Active',
    joinedDate: '2026-02-05',
    totalOrdersManaged: 512,
  },
  {
    id: 'mgr_ananya',
    name: 'Ananya Deshmukh',
    phoneNumber: '+91 98555 66778',
    email: 'ananya.biryani@foodfleet.store',
    loginId: 'MGR_BIR_05',
    assignedStoreId: 'store_biryani',
    assignedStoreName: 'Biryani Blues',
    status: 'Active',
    joinedDate: '2026-02-10',
    totalOrdersManaged: 730,
  },
  {
    id: 'mgr_vikas',
    name: 'Vikas Nair',
    phoneNumber: '+91 98666 77889',
    email: 'vikas.chai@foodfleet.store',
    loginId: 'MGR_CHAI_06',
    assignedStoreId: 'store_chaipoint',
    assignedStoreName: 'Chai Point & Snacks',
    status: 'Active',
    joinedDate: '2026-02-12',
    totalOrdersManaged: 910,
  },
  {
    id: 'mgr_neha',
    name: 'Neha Singh',
    phoneNumber: '+91 98777 88990',
    email: 'neha.momo@foodfleet.store',
    loginId: 'MGR_MOMO_07',
    assignedStoreId: 'store_wowmomo',
    assignedStoreName: 'Wow! Momo',
    status: 'Inactive',
    joinedDate: '2026-03-01',
    totalOrdersManaged: 210,
  },
  {
    id: 'mgr_karan',
    name: 'Karan Mehra',
    phoneNumber: '+91 98888 99001',
    email: 'karan.rolls@foodfleet.store',
    loginId: 'MGR_ROLLS_08',
    assignedStoreId: 'store_rolls',
    assignedStoreName: 'Rolls & Bowls',
    status: 'Active',
    joinedDate: '2026-03-10',
    totalOrdersManaged: 320,
  },
];

export const INITIAL_DELIVERY_PARTNERS: DeliveryPartner[] = [
  {
    id: 'rider_01',
    name: 'Rahul',
    phoneNumber: '+91 97111 00111',
    email: 'rahul.rider@foodfleet.delivery',
    loginId: 'RIDER_101',
    accountStatus: 'Active',
    onlineStatus: 'Online',
    totalDeliveries: 124,
    totalEarnings: 4200,
    vehicleType: 'EV Bike',
    vehicleNumber: 'DL 01 AB 4521',
    rating: 4.8,
    joinedDate: '2026-01-10',
  },
  {
    id: 'rider_02',
    name: 'Arjun',
    phoneNumber: '+91 97222 00222',
    email: 'arjun.rider@foodfleet.delivery',
    loginId: 'RIDER_102',
    accountStatus: 'Active',
    onlineStatus: 'Offline',
    totalDeliveries: 98,
    totalEarnings: 3450,
    vehicleType: 'Motorcycle',
    vehicleNumber: 'HR 26 CP 8899',
    rating: 4.6,
    joinedDate: '2026-01-18',
  },
  {
    id: 'rider_03',
    name: 'Deepak Kumar',
    phoneNumber: '+91 97333 00333',
    email: 'deepak.k@foodfleet.delivery',
    loginId: 'RIDER_103',
    accountStatus: 'Active',
    onlineStatus: 'Online',
    totalDeliveries: 215,
    totalEarnings: 7850,
    vehicleType: 'Scooter',
    vehicleNumber: 'DL 08 EK 1234',
    rating: 4.9,
    joinedDate: '2026-01-05',
  },
  {
    id: 'rider_04',
    name: 'Manish Yadav',
    phoneNumber: '+91 97444 00444',
    email: 'manish.y@foodfleet.delivery',
    loginId: 'RIDER_104',
    accountStatus: 'Active',
    onlineStatus: 'Online',
    totalDeliveries: 156,
    totalEarnings: 5320,
    vehicleType: 'Motorcycle',
    vehicleNumber: 'UP 16 Z 9012',
    rating: 4.7,
    joinedDate: '2026-01-25',
  },
  {
    id: 'rider_05',
    name: 'Suraj Rawat',
    phoneNumber: '+91 97555 00555',
    email: 'suraj.r@foodfleet.delivery',
    loginId: 'RIDER_105',
    accountStatus: 'Active',
    onlineStatus: 'Online',
    totalDeliveries: 84,
    totalEarnings: 2900,
    vehicleType: 'Bicycle',
    vehicleNumber: 'ECO-CYCLE-09',
    rating: 4.5,
    joinedDate: '2026-02-14',
  },
  {
    id: 'rider_06',
    name: 'Imran Khan',
    phoneNumber: '+91 97666 00666',
    email: 'imran.k@foodfleet.delivery',
    loginId: 'RIDER_106',
    accountStatus: 'Active',
    onlineStatus: 'Offline',
    totalDeliveries: 172,
    totalEarnings: 6100,
    vehicleType: 'EV Bike',
    vehicleNumber: 'DL 03 TR 7711',
    rating: 4.8,
    joinedDate: '2026-01-12',
  },
  {
    id: 'rider_07',
    name: 'Pradeep Jha',
    phoneNumber: '+91 97777 00777',
    email: 'pradeep.j@foodfleet.delivery',
    loginId: 'RIDER_107',
    accountStatus: 'Active',
    onlineStatus: 'Online',
    totalDeliveries: 62,
    totalEarnings: 2150,
    vehicleType: 'Scooter',
    vehicleNumber: 'DL 05 Q 4321',
    rating: 4.4,
    joinedDate: '2026-02-28',
  },
  {
    id: 'rider_08',
    name: 'Gaurav Bisht',
    phoneNumber: '+91 97888 00888',
    email: 'gaurav.b@foodfleet.delivery',
    loginId: 'RIDER_108',
    accountStatus: 'Inactive',
    onlineStatus: 'Offline',
    totalDeliveries: 41,
    totalEarnings: 1400,
    vehicleType: 'Motorcycle',
    vehicleNumber: 'UK 04 AA 5544',
    rating: 3.9,
    joinedDate: '2026-02-02',
  },
  {
    id: 'rider_09',
    name: 'Ravi Teja',
    phoneNumber: '+91 97999 00999',
    email: 'ravi.t@foodfleet.delivery',
    loginId: 'RIDER_109',
    accountStatus: 'Active',
    onlineStatus: 'Online',
    totalDeliveries: 130,
    totalEarnings: 4550,
    vehicleType: 'EV Bike',
    vehicleNumber: 'DL 02 EV 9900',
    rating: 4.7,
    joinedDate: '2026-02-18',
  },
  {
    id: 'rider_10',
    name: 'Sandeep Sharma',
    phoneNumber: '+91 97000 11000',
    email: 'sandeep.s@foodfleet.delivery',
    loginId: 'RIDER_110',
    accountStatus: 'Active',
    onlineStatus: 'Offline',
    totalDeliveries: 110,
    totalEarnings: 3800,
    vehicleType: 'Motorcycle',
    vehicleNumber: 'HR 51 X 6789',
    rating: 4.6,
    joinedDate: '2026-01-30',
  },
  {
    id: 'rider_11',
    name: 'Ketan Shah',
    phoneNumber: '+91 97000 11001',
    email: 'ketan.s@foodfleet.delivery',
    loginId: 'RIDER_111',
    accountStatus: 'Active',
    onlineStatus: 'Online',
    totalDeliveries: 89,
    totalEarnings: 3100,
    vehicleType: 'Scooter',
    vehicleNumber: 'DL 12 Y 1122',
    rating: 4.5,
    joinedDate: '2026-02-22',
  },
  {
    id: 'rider_12',
    name: 'Dinesh Mali',
    phoneNumber: '+91 97000 11002',
    email: 'dinesh.m@foodfleet.delivery',
    loginId: 'RIDER_112',
    accountStatus: 'Active',
    onlineStatus: 'Online',
    totalDeliveries: 76,
    totalEarnings: 2650,
    vehicleType: 'Bicycle',
    vehicleNumber: 'ECO-CYCLE-14',
    rating: 4.6,
    joinedDate: '2026-03-02',
  },
];

export const INITIAL_CATEGORIES: MenuCategory[] = [
  // KFC Categories
  { id: 'cat_kfc_1', storeId: 'store_kfc', name: 'Burgers', displayOrder: 1 },
  { id: 'cat_kfc_2', storeId: 'store_kfc', name: 'Sides', displayOrder: 2 },
  { id: 'cat_kfc_3', storeId: 'store_kfc', name: 'Drinks', displayOrder: 3 },
  { id: 'cat_kfc_4', storeId: 'store_kfc', name: 'Buckets & Meals', displayOrder: 4 },

  // Pizza Hut Categories
  { id: 'cat_pizza_1', storeId: 'store_pizzahut', name: 'Pizzas', displayOrder: 1 },
  { id: 'cat_pizza_2', storeId: 'store_pizzahut', name: 'Sides & Garlic Breads', displayOrder: 2 },
  { id: 'cat_pizza_3', storeId: 'store_pizzahut', name: 'Beverages & Desserts', displayOrder: 3 },

  // Subway Categories
  { id: 'cat_subway_1', storeId: 'store_subway', name: '6 Inch Subs', displayOrder: 1 },
  { id: 'cat_subway_2', storeId: 'store_subway', name: 'Footlong Subs', displayOrder: 2 },
  { id: 'cat_subway_3', storeId: 'store_subway', name: 'Cookies & Drinks', displayOrder: 3 },

  // Biryani Categories
  { id: 'cat_biryani_1', storeId: 'store_biryani', name: 'Dum Biryani', displayOrder: 1 },
  { id: 'cat_biryani_2', storeId: 'store_biryani', name: 'Starters & Kebabs', displayOrder: 2 },
  { id: 'cat_biryani_3', storeId: 'store_biryani', name: 'Desserts', displayOrder: 3 },

  // Chai Point Categories
  { id: 'cat_chai_1', storeId: 'store_chaipoint', name: 'Chai & Coffee', displayOrder: 1 },
  { id: 'cat_chai_2', storeId: 'store_chaipoint', name: 'Snacks & Buns', displayOrder: 2 },
  { id: 'cat_chai_3', storeId: 'store_chaipoint', name: 'Maggi & Quick Bites', displayOrder: 3 },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // KFC Items
  {
    id: 'item_kfc_1',
    storeId: 'store_kfc',
    categoryId: 'cat_kfc_1',
    categoryName: 'Burgers',
    name: 'Chicken Burger',
    description: 'Signature crispy chicken fillet with fresh lettuce and mayo in a toasted bun.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&auto=format&fit=crop&q=80',
    price: 129,
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 12,
  },
  {
    id: 'item_kfc_2',
    storeId: 'store_kfc',
    categoryId: 'cat_kfc_1',
    categoryName: 'Burgers',
    name: 'Veg Burger',
    description: 'Crispy seasoned vegetable patty with fresh tomatoes, lettuce, and tangy mayo.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=300&auto=format&fit=crop&q=80',
    price: 99,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 10,
  },
  {
    id: 'item_kfc_3',
    storeId: 'store_kfc',
    categoryId: 'cat_kfc_2',
    categoryName: 'Sides',
    name: 'French Fries',
    description: 'Crispy golden potato fries lightly seasoned with sea salt.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=300&auto=format&fit=crop&q=80',
    price: 89,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 6,
  },
  {
    id: 'item_kfc_4',
    storeId: 'store_kfc',
    categoryId: 'cat_kfc_2',
    categoryName: 'Sides',
    name: 'Hot & Crispy Wings (4 pcs)',
    description: 'Tender chicken wings fried to perfection with KFC secret spice blend.',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=300&auto=format&fit=crop&q=80',
    price: 169,
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 14,
  },
  {
    id: 'item_kfc_5',
    storeId: 'store_kfc',
    categoryId: 'cat_kfc_3',
    categoryName: 'Drinks',
    name: 'Pepsi (500ml)',
    description: 'Chilled sparkling refreshing Pepsi pet bottle.',
    image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=300&auto=format&fit=crop&q=80',
    price: 50,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 2,
  },
  {
    id: 'item_kfc_6',
    storeId: 'store_kfc',
    categoryId: 'cat_kfc_4',
    categoryName: 'Buckets & Meals',
    name: 'Friendship Bucket (6 pcs)',
    description: '6 pieces of signature Hot & Crispy fried chicken + 2 dips.',
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=300&auto=format&fit=crop&q=80',
    price: 499,
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 18,
  },

  // Pizza Hut Items
  {
    id: 'item_piz_1',
    storeId: 'store_pizzahut',
    categoryId: 'cat_pizza_1',
    categoryName: 'Pizzas',
    name: 'Margherita Pan Pizza (Medium)',
    description: 'Classic cheese and herb tomato sauce on signature fluffy pan crust.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=300&auto=format&fit=crop&q=80',
    price: 249,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 15,
  },
  {
    id: 'item_piz_2',
    storeId: 'store_pizzahut',
    categoryId: 'cat_pizza_1',
    categoryName: 'Pizzas',
    name: 'Spiced Chicken Feast Pan Pizza',
    description: 'Loaded with spicy tandoori chicken chunks, onions, green chilies and mozzarella.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=300&auto=format&fit=crop&q=80',
    price: 349,
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 18,
  },
  {
    id: 'item_piz_3',
    storeId: 'store_pizzahut',
    categoryId: 'cat_pizza_2',
    categoryName: 'Sides & Garlic Breads',
    name: 'Cheesy Garlic Bread',
    description: 'Freshly baked baguette slices toasted with garlic butter and melted mozzarella cheese.',
    image: 'https://images.unsplash.com/photo-1619881589775-94676579893d?w=300&auto=format&fit=crop&q=80',
    price: 139,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 10,
  },
  {
    id: 'item_piz_4',
    storeId: 'store_pizzahut',
    categoryId: 'cat_pizza_3',
    categoryName: 'Beverages & Desserts',
    name: 'Choco Lava Cake',
    description: 'Warm chocolate cake with a molten chocolate center.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=300&auto=format&fit=crop&q=80',
    price: 99,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 5,
  },

  // Subway Items
  {
    id: 'item_sub_1',
    storeId: 'store_subway',
    categoryId: 'cat_subway_1',
    categoryName: '6 Inch Subs',
    name: 'Paneer Tikka Sub (6 Inch)',
    description: 'Spiced paneer cubes with crisp bell peppers, onion and mint mayo on multigrain bread.',
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=300&auto=format&fit=crop&q=80',
    price: 189,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 8,
  },
  {
    id: 'item_sub_2',
    storeId: 'store_subway',
    categoryId: 'cat_subway_1',
    categoryName: '6 Inch Subs',
    name: 'Roasted Chicken Breast Sub (6 Inch)',
    description: 'Juicy roasted chicken slices with crunchy veggies and honey mustard.',
    image: 'https://images.unsplash.com/photo-1554433607-66b5efe9d304?w=300&auto=format&fit=crop&q=80',
    price: 219,
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 8,
  },

  // Biryani Blues Items
  {
    id: 'item_bir_1',
    storeId: 'store_biryani',
    categoryId: 'cat_biryani_1',
    categoryName: 'Dum Biryani',
    name: 'Hyderabadi Chicken Dum Biryani',
    description: 'Fragrant basmati rice layered with succulent marinated chicken and authentic spices.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300&auto=format&fit=crop&q=80',
    price: 269,
    isVeg: false,
    isAvailable: true,
    preparationTimeMinutes: 15,
  },
  {
    id: 'item_bir_2',
    storeId: 'store_biryani',
    categoryId: 'cat_biryani_1',
    categoryName: 'Dum Biryani',
    name: 'Paneer Dum Biryani',
    description: 'Royal spices infused in basmati rice with soft cottage cheese cubes and fried onions.',
    image: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=300&auto=format&fit=crop&q=80',
    price: 229,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 15,
  },

  // Chai Point Items
  {
    id: 'item_chai_1',
    storeId: 'store_chaipoint',
    categoryId: 'cat_chai_1',
    categoryName: 'Chai & Coffee',
    name: 'Ginger Cardamom Chai (Flask 500ml)',
    description: 'Freshly brewed hot tea infused with crushed ginger and aromatic cardamom pods.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&auto=format&fit=crop&q=80',
    price: 110,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 8,
  },
  {
    id: 'item_chai_2',
    storeId: 'store_chaipoint',
    categoryId: 'cat_chai_2',
    categoryName: 'Snacks & Buns',
    name: 'Butter Bun Maska + Samosa (2 pcs)',
    description: 'Soft bakery bun stuffed with generous Amul butter, paired with crispy hot potato samosas.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&auto=format&fit=crop&q=80',
    price: 85,
    isVeg: true,
    isAvailable: true,
    preparationTimeMinutes: 5,
  },
];

export const INITIAL_ORDERS: Order[] = [
  // Example #1 from prompt: FC1024 (Out for Delivery)
  {
    id: 'FC1024',
    customerName: 'Rahul',
    customerPhone: '+91 98765 12345',
    storeId: 'store_kfc',
    storeName: 'KFC',
    items: [
      {
        id: 'oi_1',
        menuItemId: 'item_kfc_1',
        name: 'Chicken Burger',
        price: 129,
        quantity: 2,
        isVeg: false,
      },
      {
        id: 'oi_2',
        menuItemId: 'item_kfc_5',
        name: 'Pepsi',
        price: 50,
        quantity: 1,
        isVeg: true,
      },
    ],
    subtotal: 308,
    deliveryFee: 30,
    total: 338,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    deliveryPartnerId: 'rider_02',
    deliveryPartnerName: 'Arjun',
    deliveryPartnerPhone: '+91 97222 00222',
    orderStatus: 'Out for Delivery',
    orderDateTime: '2026-08-30 07:42 PM',
    deliveryAddress: {
      hostelOrPgName: 'ABC Hostel',
      roomNumber: 'Room 304',
      landmark: 'Near North Gate Water Cooler',
      fullAddress: 'Room 304, ABC Hostel, Campus North Zone, Pin 110007',
    },
    timeline: [
      {
        status: 'Waiting for Manager',
        timestamp: '2026-08-30 07:42 PM',
        actor: 'CUSTOMER',
        actorName: 'Rahul',
        note: 'Order placed by customer via app',
      },
      {
        status: 'Manager Accepted',
        timestamp: '2026-08-30 07:44 PM',
        actor: 'MANAGER',
        actorName: 'Rahul Sharma (KFC)',
        note: 'Order accepted by store manager',
      },
      {
        status: 'Preparing',
        timestamp: '2026-08-30 07:46 PM',
        actor: 'MANAGER',
        actorName: 'Rahul Sharma (KFC)',
        note: 'Kitchen started food preparation',
      },
      {
        status: 'Ready for Pickup',
        timestamp: '2026-08-30 07:56 PM',
        actor: 'MANAGER',
        actorName: 'Rahul Sharma (KFC)',
        note: 'Packed in thermal bag ready for rider',
      },
      {
        status: 'Delivery Assigned',
        timestamp: '2026-08-30 07:57 PM',
        actor: 'SYSTEM',
        actorName: 'Auto Dispatcher',
        note: 'Assigned to Arjun (Rider 102)',
      },
      {
        status: 'Picked Up',
        timestamp: '2026-08-30 08:02 PM',
        actor: 'DELIVERY_PARTNER',
        actorName: 'Arjun',
        note: 'Rider picked up parcel from KFC counter',
      },
      {
        status: 'Out for Delivery',
        timestamp: '2026-08-30 08:04 PM',
        actor: 'DELIVERY_PARTNER',
        actorName: 'Arjun',
        note: 'Rider enroute to ABC Hostel Room 304',
      },
    ],
  },

  // Example #2: Manager Timeout order requiring ADMIN INTERVENTION!
  {
    id: 'FC1028',
    customerName: 'Sneha Kapoor',
    customerPhone: '+91 98123 77665',
    storeId: 'store_burgerking',
    storeName: 'Burger King',
    items: [
      {
        id: 'oi_3',
        menuItemId: 'item_kfc_1',
        name: 'Crispy Veg Whopper Meal',
        price: 219,
        quantity: 1,
        isVeg: true,
      },
      {
        id: 'oi_4',
        menuItemId: 'item_kfc_3',
        name: 'Peri Peri Fries',
        price: 99,
        quantity: 1,
        isVeg: true,
      },
    ],
    subtotal: 318,
    deliveryFee: 30,
    total: 348,
    paymentMethod: 'UPI / Online',
    paymentStatus: 'Paid',
    orderStatus: 'Waiting for Admin',
    isTimeoutInterventionRequired: true,
    timeoutAt: '2026-08-30 08:15 PM',
    orderDateTime: '2026-08-30 08:10 PM',
    deliveryAddress: {
      hostelOrPgName: 'Silver Palms PG (Block B)',
      roomNumber: 'Room 214',
      landmark: 'Opposite Central Library',
      fullAddress: 'Room 214, Silver Palms PG Block B, Tech Hub Road',
    },
    timeline: [
      {
        status: 'Waiting for Manager',
        timestamp: '2026-08-30 08:10 PM',
        actor: 'CUSTOMER',
        actorName: 'Sneha Kapoor',
        note: 'Customer placed order with UPI payment',
      },
      {
        status: 'Manager Timeout',
        timestamp: '2026-08-30 08:15 PM',
        actor: 'SYSTEM',
        note: 'Store manager failed to respond within 5 min timeout threshold',
      },
      {
        status: 'Waiting for Admin',
        timestamp: '2026-08-30 08:15 PM',
        actor: 'SYSTEM',
        note: 'Escalated to Admin Panel for manual approval or cancellation',
      },
    ],
  },

  // Example #3: Another Manager Timeout order
  {
    id: 'FC1029',
    customerName: 'Aditya Sen',
    customerPhone: '+91 98321 44556',
    storeId: 'store_biryani',
    storeName: 'Biryani Blues',
    items: [
      {
        id: 'oi_5',
        menuItemId: 'item_bir_1',
        name: 'Hyderabadi Chicken Dum Biryani',
        price: 269,
        quantity: 2,
        isVeg: false,
      },
    ],
    subtotal: 538,
    deliveryFee: 30,
    discountAmount: 50,
    total: 518,
    paymentMethod: 'UPI / Online',
    paymentStatus: 'Paid',
    orderStatus: 'Waiting for Admin',
    isTimeoutInterventionRequired: true,
    timeoutAt: '2026-08-30 08:22 PM',
    orderDateTime: '2026-08-30 08:17 PM',
    deliveryAddress: {
      hostelOrPgName: 'Boys Hostel 4',
      roomNumber: 'Room 108',
      landmark: 'Ground Floor, Wing A',
      fullAddress: 'Room 108, Wing A, Boys Hostel 4, University Campus',
    },
    timeline: [
      {
        status: 'Waiting for Manager',
        timestamp: '2026-08-30 08:17 PM',
        actor: 'CUSTOMER',
        actorName: 'Aditya Sen',
        note: 'Order placed with coupon code FLAT50',
      },
      {
        status: 'Manager Timeout',
        timestamp: '2026-08-30 08:22 PM',
        actor: 'SYSTEM',
        note: 'Store manager unattended notification timeout',
      },
      {
        status: 'Waiting for Admin',
        timestamp: '2026-08-30 08:22 PM',
        actor: 'SYSTEM',
        note: 'Urgent: Awaiting admin intervention to accept/reject',
      },
    ],
  },

  // Example #4: Preparing order
  {
    id: 'FC1025',
    customerName: 'Divya Nambiar',
    customerPhone: '+91 98456 99887',
    storeId: 'store_pizzahut',
    storeName: 'Pizza Hut',
    items: [
      {
        id: 'oi_6',
        menuItemId: 'item_piz_1',
        name: 'Margherita Pan Pizza (Medium)',
        price: 249,
        quantity: 1,
        isVeg: true,
      },
      {
        id: 'oi_7',
        menuItemId: 'item_piz_3',
        name: 'Cheesy Garlic Bread',
        price: 139,
        quantity: 1,
        isVeg: true,
      },
    ],
    subtotal: 388,
    deliveryFee: 30,
    total: 418,
    paymentMethod: 'UPI / Online',
    paymentStatus: 'Paid',
    orderStatus: 'Preparing',
    orderDateTime: '2026-08-30 07:55 PM',
    deliveryAddress: {
      hostelOrPgName: 'Kaveri Girls Hostel',
      roomNumber: 'Room 412',
      landmark: '4th Floor near lift',
      fullAddress: 'Room 412, Kaveri Girls Hostel, South Campus',
    },
    timeline: [
      {
        status: 'Waiting for Manager',
        timestamp: '2026-08-30 07:55 PM',
        actor: 'CUSTOMER',
        actorName: 'Divya Nambiar',
        note: 'Order placed',
      },
      {
        status: 'Manager Accepted',
        timestamp: '2026-08-30 07:57 PM',
        actor: 'MANAGER',
        actorName: 'Priya Patel (Pizza Hut)',
        note: 'Manager accepted order',
      },
      {
        status: 'Preparing',
        timestamp: '2026-08-30 07:58 PM',
        actor: 'MANAGER',
        actorName: 'Priya Patel (Pizza Hut)',
        note: 'Pizza in oven, estimated 15 mins',
      },
    ],
  },

  // Example #5: Ready for Pickup
  {
    id: 'FC1026',
    customerName: 'Karan Joshi',
    customerPhone: '+91 98666 11223',
    storeId: 'store_subway',
    storeName: 'Subway',
    items: [
      {
        id: 'oi_8',
        menuItemId: 'item_sub_1',
        name: 'Paneer Tikka Sub (6 Inch)',
        price: 189,
        quantity: 1,
        isVeg: true,
      },
      {
        id: 'oi_9',
        menuItemId: 'item_sub_2',
        name: 'Roasted Chicken Breast Sub (6 Inch)',
        price: 219,
        quantity: 1,
        isVeg: false,
      },
    ],
    subtotal: 408,
    deliveryFee: 30,
    total: 438,
    paymentMethod: 'UPI / Online',
    paymentStatus: 'Paid',
    deliveryPartnerId: 'rider_01',
    deliveryPartnerName: 'Rahul',
    deliveryPartnerPhone: '+91 97111 00111',
    orderStatus: 'Ready for Pickup',
    orderDateTime: '2026-08-30 07:48 PM',
    deliveryAddress: {
      hostelOrPgName: 'Green Meadows PG',
      roomNumber: 'Flat 102',
      landmark: 'Behind Canteen',
      fullAddress: 'Flat 102, Green Meadows PG, Main St',
    },
    timeline: [
      {
        status: 'Waiting for Manager',
        timestamp: '2026-08-30 07:48 PM',
        actor: 'CUSTOMER',
        actorName: 'Karan Joshi',
      },
      {
        status: 'Manager Accepted',
        timestamp: '2026-08-30 07:50 PM',
        actor: 'MANAGER',
        actorName: 'Amit Verma (Subway)',
      },
      {
        status: 'Preparing',
        timestamp: '2026-08-30 07:51 PM',
        actor: 'MANAGER',
      },
      {
        status: 'Delivery Assigned',
        timestamp: '2026-08-30 07:55 PM',
        actor: 'SYSTEM',
        note: 'Assigned to Rahul (Rider 101)',
      },
      {
        status: 'Ready for Pickup',
        timestamp: '2026-08-30 08:00 PM',
        actor: 'MANAGER',
        note: 'Packed and waiting on counter',
      },
    ],
  },

  // Example #6: Delivered order
  {
    id: 'FC1020',
    customerName: 'Tanvi Shah',
    customerPhone: '+91 98777 55443',
    storeId: 'store_chaipoint',
    storeName: 'Chai Point & Snacks',
    items: [
      {
        id: 'oi_10',
        menuItemId: 'item_chai_1',
        name: 'Ginger Cardamom Chai (Flask 500ml)',
        price: 110,
        quantity: 1,
        isVeg: true,
      },
      {
        id: 'oi_11',
        menuItemId: 'item_chai_2',
        name: 'Butter Bun Maska + Samosa (2 pcs)',
        price: 85,
        quantity: 2,
        isVeg: true,
      },
    ],
    subtotal: 280,
    deliveryFee: 25,
    total: 305,
    paymentMethod: 'UPI / Online',
    paymentStatus: 'Paid',
    deliveryPartnerId: 'rider_03',
    deliveryPartnerName: 'Deepak Kumar',
    deliveryPartnerPhone: '+91 97333 00333',
    orderStatus: 'Delivered',
    orderDateTime: '2026-08-30 06:30 PM',
    deliveryAddress: {
      hostelOrPgName: 'Sarojini Bhawan',
      roomNumber: 'Room 501',
      landmark: 'Top floor terrace entry',
      fullAddress: 'Room 501, Sarojini Bhawan Hostel, North Campus',
    },
    timeline: [
      { status: 'Waiting for Manager', timestamp: '2026-08-30 06:30 PM', actor: 'CUSTOMER' },
      { status: 'Manager Accepted', timestamp: '2026-08-30 06:32 PM', actor: 'MANAGER' },
      { status: 'Preparing', timestamp: '2026-08-30 06:33 PM', actor: 'MANAGER' },
      { status: 'Ready for Pickup', timestamp: '2026-08-30 06:40 PM', actor: 'MANAGER' },
      { status: 'Delivery Assigned', timestamp: '2026-08-30 06:41 PM', actor: 'SYSTEM' },
      { status: 'Picked Up', timestamp: '2026-08-30 06:45 PM', actor: 'DELIVERY_PARTNER' },
      { status: 'Out for Delivery', timestamp: '2026-08-30 06:47 PM', actor: 'DELIVERY_PARTNER' },
      { status: 'Delivered', timestamp: '2026-08-30 07:02 PM', actor: 'DELIVERY_PARTNER', note: 'Handed over to customer' },
    ],
  },

  // Example #7: Cancelled order
  {
    id: 'FC1018',
    customerName: 'Rohan Mehra',
    customerPhone: '+91 98888 22331',
    storeId: 'store_kfc',
    storeName: 'KFC',
    items: [
      {
        id: 'oi_12',
        menuItemId: 'item_kfc_6',
        name: 'Friendship Bucket (6 pcs)',
        price: 499,
        quantity: 1,
        isVeg: false,
      },
    ],
    subtotal: 499,
    deliveryFee: 35,
    total: 534,
    paymentMethod: 'UPI / Online',
    paymentStatus: 'Refunded',
    orderStatus: 'Cancelled',
    cancellationReason: 'Item out of stock during peak hour',
    orderDateTime: '2026-08-30 05:15 PM',
    deliveryAddress: {
      hostelOrPgName: 'Tagore Hostel',
      roomNumber: 'Room 205',
      fullAddress: 'Room 205, Tagore Hostel, East Campus',
    },
    timeline: [
      { status: 'Waiting for Manager', timestamp: '2026-08-30 05:15 PM', actor: 'CUSTOMER' },
      {
        status: 'Cancelled',
        timestamp: '2026-08-30 05:22 PM',
        actor: 'MANAGER',
        actorName: 'Rahul Sharma',
        note: 'Order cancelled: Chicken Bucket inventory exhausted. Refund initiated.',
      },
    ],
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'off_01',
    name: 'Weekend Feast 20%',
    title: 'Weekend Feast 20%',
    description: 'Get 20% off on your favorite meals this weekend up to ₹100.',
    couponCode: 'WEEKEND20',
    discountType: 'Percentage',
    discountValue: 20,
    minOrderValue: 299,
    maxDiscount: 100,
    applicableStoreIds: ['store_kfc'],
    applicableStoreNames: ['KFC'],
    startDate: '2026-08-30',
    endDate: '2026-09-07',
    status: 'Active',
    isActive: true,
    usageCount: 148,
    totalSavingsGiven: 12400,
  },
  {
    id: 'off_02',
    name: 'Flat ₹50 Super Saver',
    title: 'Flat ₹50 Super Saver',
    description: 'Flat ₹50 discount on orders above ₹249 on all stores.',
    couponCode: 'FLAT50',
    discountType: 'Fixed Amount',
    discountValue: 50,
    minOrderValue: 249,
    applicableStoreIds: ['ALL'],
    applicableStoreNames: ['All Stores'],
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    status: 'Active',
    isActive: true,
    usageCount: 420,
    totalSavingsGiven: 21000,
  },
  {
    id: 'off_03',
    name: 'Pizza Party 30%',
    title: 'Pizza Party 30%',
    description: 'Enjoy 30% discount on Pan Pizzas and Sides at Pizza Hut.',
    couponCode: 'PIZZAPARTY',
    discountType: 'Percentage',
    discountValue: 30,
    minOrderValue: 399,
    maxDiscount: 150,
    applicableStoreIds: ['store_pizzahut'],
    applicableStoreNames: ['Pizza Hut'],
    startDate: '2026-08-15',
    endDate: '2026-09-15',
    status: 'Active',
    isActive: true,
    usageCount: 96,
    totalSavingsGiven: 11520,
  },
  {
    id: 'off_04',
    name: 'Welcome Campus ₹75',
    title: 'Welcome Campus ₹75',
    description: 'Special welcome discount for freshers and hostellers.',
    couponCode: 'CAMPUS75',
    discountType: 'Fixed Amount',
    discountValue: 75,
    minOrderValue: 349,
    applicableStoreIds: ['ALL'],
    applicableStoreNames: ['All Stores'],
    startDate: '2026-07-01',
    endDate: '2026-08-15',
    status: 'Inactive',
    isActive: false,
    usageCount: 310,
    totalSavingsGiven: 23250,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationLog[] = [
  {
    id: 'notif_01',
    title: 'Weekend Offer 🎉',
    message: 'Get 20% off on selected stores this weekend! Use code WEEKEND20.',
    targetAudience: 'All Customers',
    sentAt: '2026-08-30 05:00 PM',
    sentBy: 'Vikramaditya Rao (Admin)',
    status: 'Sent',
    selectedRecipientsCount: 1450,
  },
  {
    id: 'notif_02',
    title: 'Rain Surge Incentive 🌧️',
    message: 'Earn extra ₹25 per completed order between 7 PM and 11 PM tonight.',
    targetAudience: 'All Delivery Partners',
    sentAt: '2026-08-29 06:30 PM',
    sentBy: 'Vikramaditya Rao (Admin)',
    status: 'Sent',
    selectedRecipientsCount: 12,
  },
  {
    id: 'notif_03',
    title: 'Peak Dinner Hour Advisory',
    message: 'Please ensure high inventory prep for weekend night rush.',
    targetAudience: 'All Store Owners/Managers',
    sentAt: '2026-08-29 04:00 PM',
    sentBy: 'Vikramaditya Rao (Admin)',
    status: 'Sent',
    selectedRecipientsCount: 8,
  },
  {
    id: 'notif_04',
    title: 'Fresh Biryani Available Now!',
    message: 'Hot authentic Dum Biryani from Biryani Blues is just 15 mins away.',
    targetAudience: 'Customers of a Selected Store',
    storeId: 'store_biryani',
    storeName: 'Biryani Blues',
    sentAt: '2026-08-28 12:45 PM',
    sentBy: 'Vikramaditya Rao (Admin)',
    status: 'Sent',
    selectedRecipientsCount: 320,
  },
];
